# Generated by Django 3.2.4 on 2021-07-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='completed',
            new_name='complete',
        ),
    ]
